'use client'

import { Download, RotateCcw, Share2 } from 'lucide-react'
import { Button } from '@/components/ui/button'

export function CalculatorActions({
  title,
  onReset,
  getShareText,
  getReportText,
}: {
  title: string
  onReset: () => void
  getShareText?: () => string
  getReportText?: () => string
}) {
  const handleShare = async () => {
    const text = getShareText?.() ?? `${title} — FinWise`
    const url = typeof window !== 'undefined' ? window.location.href : ''
    if (navigator.share) {
      try {
        await navigator.share({ title, text, url })
        return
      } catch {
        /* fall through */
      }
    }
    await navigator.clipboard.writeText(`${text}\n${url}`)
  }

  const handleDownload = () => {
    const text = getReportText?.() ?? `${title}\n\nGenerated by FinWise`
    const blob = new Blob([text], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${title.toLowerCase().replace(/\s+/g, '-')}-report.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="flex flex-wrap gap-2 border-t border-border pt-4">
      <Button type="button" variant="outline" size="sm" onClick={onReset}>
        <RotateCcw className="mr-2 h-4 w-4" />
        Reset
      </Button>
      <Button type="button" variant="outline" size="sm" onClick={handleShare}>
        <Share2 className="mr-2 h-4 w-4" />
        Share
      </Button>
      <Button type="button" variant="outline" size="sm" onClick={handleDownload}>
        <Download className="mr-2 h-4 w-4" />
        Download
      </Button>
    </div>
  )
}
